Feature/UI lib create modal variant based on blueprint new modals UI cu 2ad6kf0
perimetre/ui pull request #66
Opened 2022-06-01 13:41 UTC by lcscou

- [x] Have you made sure your branch is up to date with it's parent branch before creating this PR?
- [x] Are all warnings and errors fixed?
- [x] Have you throughoutfully commented your changes?
- [x] Have you added proper jsdocs comments?
- [x] Have you updated the **CHANGELOG** file?
  - [x] Have all _**breaking changes**_ been properly documented and communicated?
  - [x] Have all _changes_ been properly documented and communicated?
  - [x] Have all _fixed issues_ been properly documented and communicated?
- [x] **Have you raised the `version` in package.json if applicable?**
- [x] Have you randomly paid a compliment to a colleague today?

---

- [x] **Do you agree that by pushing to master(if the case). You'll generate a new package build?**

2022-06-01 13:41 UTC, yanikproulx commented
Task linked: [CU-2ad6kf0 [UI lib] Create modal variant based on blueprint new modals UI](https://app.clickup.com/t/2ad6kf0)

2022-06-02 14:42 UTC, adarleyjrr requested changes
Just a few notes, thank you!

2022-06-02 14:42 UTC, adarleyjrr commented on src/components/Modal/index.tsx
> +  variant?: 'Default' | 'New';
`variant?: 'default' | 'new';`

2022-06-02 14:42 UTC, adarleyjrr commented on src/components/Modal/index.tsx
> +   * Whether or not close button should be displayed
Please update this comment to also specify that modal is not closable if this is set.

2022-06-02 14:42 UTC, adarleyjrr commented on src/components/Modal/index.tsx
> +   * Whether the content container should be removed
I don't think this is what the prop does, please redo this comment.

2022-06-02 14:42 UTC, adarleyjrr commented on src/components/Modal/index.tsx
> + * @param props.removePadding Whether content container should be removed
Update these guys too when you do the updates above.

2022-06-02 14:42 UTC, adarleyjrr commented on src/components/Modal/index.css
> +    &.New {
`&.new`

2022-06-02 14:42 UTC, adarleyjrr commented on src/components/Modal/index.tsx
> +        <div className={classnames('pui-modal-container', variant)}>
`<div className={classnames('pui-modal-container', { 'new': variant === 'new' })}>`

2022-06-03 13:54 UTC, adarleyjrr commented on src/components/Modal/index.tsx
> +  variant = 'Default',
Please replace for `variant = 'default'`. Is your TypeScript running? That assignment should have raised an error.

2022-06-03 13:56 UTC, adarleyjrr commented on src/components/Modal/index.tsx
> +   * If yes. It won't push the content down and the hasPadding should be set on the children component.
`hasPadding` does not exist anymore. I think this comment should remain `If yes. It won't push the content down and the padding should be set on the children component.`? I am not sure, please just make it clear according to the actual behaviour after your changes were made.

2022-06-03 14:22 UTC, adarleyjrr approved these changes
LGTM!

2022-06-03 16:20 UTC, merged